version: "3.9"
services:
  postgres:
    build: .
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
volumes:
  postgres:
